# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^config'
      - '^doc'
      - '^test'
      - '^Merge'
brews:
  - tap:
      owner: CamiloGarciaLaRotta
      name: homebrew-brews
    folder: Formula
    homepage: https://github.com/CamiloGarciaLaRotta/kboard
    description: Terminal game to practice keyboard typing
    test: |
      system "#{bin}/kboard -h"
