# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^doc'
      - '^test'
brews:
  - tap:
      owner: CamiloGarciaLaRotta
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/CamiloGarciaLaRotta/kboard
    description: Terminal game to practice keyboard typing
    test: |
      system "#{bin}/kboard"
